# Generated by Django 5.2.9 on 2025-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Användarnman måte vara unik/inte tom', max_length=100, unique=True)),
            ],
        ),
    ]
